# Generated by Django 6.0 on 2026-01-03 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='queue_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
