# Generated by Django 6.0 on 2026-01-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_token_queue_date_alter_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
