# Generated by Django 6.0.1 on 2026-01-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0003_token_served_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='rescheduled_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='slot_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='slot_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('SERVING', 'Serving'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], default='WAITING', max_length=10),
        ),
    ]
