# Generated by Django 6.0.1 on 2026-01-19 14:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0004_token_cancelled_at_token_rescheduled_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_date', models.DateField(default=datetime.date.today)),
                ('extra_minutes', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_app.counter')),
            ],
        ),
    ]
