# Generated by Django 6.0.1 on 2026-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0005_counterdelay'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='near_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
